### ISSUE TITLE
公式1的疑问

### ISSUE THREAD

**Issue by shuangzixing** [corwinliu9669/Learning-a-Few-shot-Embedding-Model-with-Contrastive-Learning#1]
您好，我阅读您的论文时，有点疑问，在Episodic contrastive learning小结中，您通过的公式1构建了对比学习。然而，在one-shot的情况下公式1就是episodic training loss，我没有明白对比学习和eposide training loss的区别。在5-shot的情况下，您分别考虑每个query样本和每个support样本的相似度，并没有像CAN一样类别取均值后计算相似度，然而，据我所知，这种每个样本分别计算相似的方法在早期的matching network就是如此进行的。因此对比学习是否就是早期逐样本的episodic training loss。期待您的解答。感谢。

**Comment by corwinliu9669** [comment]
您好，5-shot的情况下我的处理方式和CAN类似，先取类别均值。

**Comment by shuangzixing** [comment]
> 您好，5-shot的情况下我的处理方式和CAN类似，先取类别均值。

既然这样，公式1和CAN使用的eposide training loss有什么区别？

**Comment by corwinliu9669** [comment]
您好，如果只看公式1，形式上是差不多。我们从contrastive learning的角度来解释了为什么要使用这一项，这一项也在很多现有的工作中被使用到。此外我们没有使用CAN提出的模块，我们的contribution在文章中进行了阐述。如果您想更深入探讨，我们可以邮件或者微信进行讨论。感谢您对我们工作的关注！
