### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by xiaoky1** [corwinliu9669/Learning-a-Few-shot-Embedding-Model-with-Contrastive-Learning#2]
Dear Author, I have noticed that you use the '.pickle' files as your datasets, but I don't have such files and don't know how you divide the data into such files. Could you please share your datasets ( '.pickle' files best) ? Thanks!

**Comment by corwinliu9669** [comment]
Please refer to https://github.com/gidariss/FewShotWithoutForgetting.
