### ISSUE TITLE
Could you give the code or the parameters for tirerdImagenet to repeat the results?

### ISSUE THREAD

**Issue by xue19890510** [corwinliu9669/Learning-a-Few-shot-Embedding-Model-with-Contrastive-Learning#5]
Thank you for your great work. I want to follow your work, could you give me the code or parameter settings for the tieredImagenet  and the link where to download the datasets,  thank you very much.

**Comment by corwinliu9669** [comment]
For tiered settings, please refer to the experiment section of the paper.  For tieredminiImageNet dataset, please refer to https://github.com/yaoyao-liu/tiered-imagenet-tools.
